---
meta:
  google:
    zones:
      z1: (( param "What Google zone should your concourse VMs be in?" ))

resource_pools:
  - name: web
    network: concourse
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      machine_type: n1-standard-2
      zone: (( grab meta.google.zones.z1 ))

  - name: db
    network: concourse
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      machine_type: n1-standard-2
      zone: (( grab meta.google.zones.z1 ))

  - name: workers
    network: concourse
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      machine_type: n1-standard-4
      zone: (( grab meta.google.zones.z1 ))

  - name: haproxy
    network: concourse
    stemcell: (( grab meta.stemcell ))
    cloud_properties:
      machine_type: n1-standard-2
      zone: (( grab meta.google.zones.z1 ))

compilation:
  workers: 3
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    machine_type: n1-standard-4
    zone: (( grab meta.google.zones.z1 ))

jobs:
  - name: haproxy
    resource_pool: haproxy
  - name: web
    resource_pool: web
  - name: db
    resource_pool: db
  - name: worker
    resource_pool: workers
